# coding: utf-8

"""
    JCDecaux API

    JCDecaux API for retrieving dynamic data about bike stations and contracts  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: alesanchezmedina@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

from sys import path
import os
from os.path import dirname as dir

path.append(dir(path[0]))
import importlib

import unittest

from skill.connectors import bikes_api
from skill.connectors.bikes_api.api.contracts_api import ContractsApi  # noqa: E501
from skill.connectors.bikes_api.models.contract import Contract
from skill.connectors.bikes_api.rest import ApiException
import configuration

class TestContractsApi(unittest.TestCase):
    """ContractsApi unit test stubs"""

    def setUp(self):
        api_config = bikes_api.Configuration()
        api_config.api_key['apiKey'] = configuration.JCDECAUX_KEY

        self.api = bikes_api.api.contracts_api.ContractsApi(
                bikes_api.ApiClient(configuration=api_config)
            )  # noqa: E501

    def tearDown(self):
        pass

    def test_contracts_get(self):
        """Test case for contracts_get

        Gets the full list of JCDecaux contracts  # noqa: E501
        """
        self.api.contracts_get()
    
    def test_contracts_get_type(self):
        """Test case for contracts_get

        Assert the API returns a list  # noqa: E501
        """
        contracts = self.api.contracts_get()

        self.assertTrue(isinstance(contracts, list))

    def test_contracts_get_elements_type(self):
        """Test case for contracts_get

        Assert the API returns a list of objects # noqa: E501
        """
        contracts = self.api.contracts_get()

        self.assertTrue(isinstance(contracts[0], Contract))


if __name__ == '__main__':
    unittest.main()
