# coding: utf-8

"""
    JCDecaux API

    JCDecaux API for retrieving dynamic data about bike stations and contracts  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: alesanchezmedina@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

from sys import path
import os
from os.path import dirname as dir

path.append(dir(path[0]))
import importlib

import unittest

from skill.connectors import bikes_api
from skill.connectors.bikes_api.models.contract import Contract  # noqa: E501
from skill.connectors.bikes_api.rest import ApiException
import configuration

class TestContract(unittest.TestCase):
    """Contract unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContract(self):
        """Test Contract"""
        Contract(
            name="Rouen",
            commercial_name="cy'clic",
            cities=[
                "Rouen"
            ],
            country_code="FR"
        )

if __name__ == '__main__':
    unittest.main()
