# coding: utf-8

"""
    JCDecaux API

    JCDecaux API for retrieving dynamic data about bike stations and contracts  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: alesanchezmedina@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

from lambda import bikes_api
from bikes_api.api.contracts_api import ContractsApi  # noqa: E501
from bikes_api.rest import ApiException


class TestContractsApi(unittest.TestCase):
    """ContractsApi unit test stubs"""

    def setUp(self):
        self.api = bikes_api.api.contracts_api.ContractsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contracts_get(self):
        """Test case for contracts_get

        Gets the full list of JCDecaux contracts  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
