language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
cache: pip
before_install:
  - openssl aes-256-cbc -K $encrypted_18eace9e5aeb_key -iv $encrypted_18eace9e5aeb_iv -in test/configuration.py.enc -out test/configuration.py -d
  - pip install poetry
install:
  - poetry install
script:
  - poetry run python test/bikes_test.py
notifications:
  email:
    recipients:
      - alesanchezmedina@gmail.com
    on_success: never
    on_failure: always
